#
# Basic zsh setup
#

# Load zgen
source "${HOME}/.zgen/zgen.zsh"

# check if there's no init script
if ! zgen saved; then
  # load oh my zsh
  zgen oh-my-zsh
  zgen oh-my-zsh plugins/brew
  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/osx
  zgen oh-my-zsh plugins/sudo
  zgen oh-my-zsh plugins/vagrant

  zgen load zsh-users/zsh-syntax-highlighting
  zgen load zsh-users/zsh-history-substring-search
  zgen load zsh-users/zsh-completions src
  zgen load RobSis/zsh-completion-generator

  zgen oh-my-zsh themes/sorin

  zgen save
fi

# Match standard stuff + camel case
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:[^A-Z0-9]||[A-Z0-9]=** r:|=*' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# Source Start-up .zsh scripts
DOTFILES_SCRIPTS_PATH="$HOME/.zsh.dotfiles_scripts"
if [[ -d "$DOTFILES_SCRIPTS_PATH" ]]; then
  for config_file ($DOTFILES_SCRIPTS_PATH/*.zsh); do
    source $config_file
  done
fi

# Source User .zsh scripts
USER_SCRIPTS_PATH="$HOME/.zsh.custom_scripts"
if [[ -d "$USER_SCRIPTS_PATH" ]]; then
  for config_file ($USER_SCRIPTS_PATH/*.zsh); do
    source $config_file
  done
fi

# Finally, set extended globbing
setopt extendedglob

