# History settings
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob

# Emacs bindings
bindkey -e

# The following lines were added by compinstall
zstyle :compinstall filename '/Users/tomaszj/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
