#
# Basic zsh setup
#

export COMPLETION_WAITING_DOTS="true"

# Load zgen
source "${HOME}/.zgen/zgen.zsh"

# check if there's no init script
if ! zgen saved; then
  # load oh my zsh
  zgen oh-my-zsh
  zgen oh-my-zsh plugins/brew
  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/osx
  zgen oh-my-zsh plugins/fzf
  zgen oh-my-zsh plugins/sudo
  zgen oh-my-zsh plugins/colored-man-pages
  zgen oh-my-zsh plugins/kubectl

  zgen load zsh-users/zsh-syntax-highlighting
  zgen load zsh-users/zsh-history-substring-search
  zgen load zsh-users/zsh-completions src
  zgen load RobSis/zsh-completion-generator

  zgen load MichaelAquilina/zsh-you-should-use

  # supercrabtree/k replacement to use `j` as a command
  zgen load tomaszj/j

  zgen oh-my-zsh themes/sorin

  zgen save
fi

# Match standard stuff + camel case
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:[^A-Z0-9]||[A-Z0-9]=** r:|=*' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# Source Start-up .zsh scripts
DOTFILES_SCRIPTS_PATH="$HOME/.zsh.dotfiles_scripts"
if [[ -d "$DOTFILES_SCRIPTS_PATH" ]]; then
  for config_file ($DOTFILES_SCRIPTS_PATH/*.zsh); do
    source $config_file
  done
fi

# Source User .zsh scripts if not empty
USER_SCRIPTS_PATH="$HOME/.zsh.custom_scripts"
if [[ -d "$USER_SCRIPTS_PATH" && "$(ls -A $USER_SCRIPTS_PATH)" ]]; then
  for config_file ($USER_SCRIPTS_PATH/*.zsh); do
    source $config_file
  done
fi

# Finally, set extended globbing
setopt extendedglob


# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
